#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Send to ~/.local/share/dwm/autostart.sh
# xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
# setbg &			# set the background with the `setbg` script
# xrdb merge /home/thomaz/.local/src/sixel-st/xresources # update terminal colors
# localsend --hidden &

# autostart="unclutter remapd"

# for program in $autostart; do
# 	pidof -sx "$program" || "$program" &
# done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
# [ -n "$xrdbpid" ] && wait "$xrdbpid"
