#!/bin/sh
# Run gatsby developer

pkill -f "npx gatsby develop"
note "Restarting gatsby develop"
cd ~/blog
npx gatsby develop > debug.log 2>&1 &
# manually wait the develop to start
sleep 5
$BROWSER localhost:8000 > /dev/null 2>&1 &
